### ISSUE TITLE
[FEAT] Trigger events in website

### ISSUE THREAD

**Issue by jacopo-eth** [slice-so/merge-to-earn#16]
**What problem is being solved?**
There are no events set up, so we don't have data to use to improve UX.

**What is the ideal outcome?**
Events should be triggered for most important actions

**What is the proposed solution?**
Add event triggers using `saEvent`

**Comment by zerohex-eth** [comment]
Associated [PR](https://github.com/slice-so/merge-to-earn/pull/17) successfully merged
